name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on:
  push:
    branches: [ master, dev, dev-blocking, qa-elizabeth, qa-hansae, ui ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1

    # Runs a set of commands using the runners shell
    - name: Install dependencies
      run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    
    # Run our extension and make sure it launches
    - name: Build Extension
      run: npm run build  

    # Run our tests
    - name: Run Jest
      uses: mujo-code/puppeteer-headful@master
      env:
        CI: 'true'
      with:
        args: npm test
